### PR TITLE
Bug fix and new feature

### PR DESCRIPTION
**Pull request by emrebekar**
Com object write enabled. I test it with primitive types but not complex types at this moment. variant.js file heavly being changed. And a bug fix found in ndrbuffer.js file and fixed. Thank you very much for writing this library. :)

### CODE REVIEW

**Comment by steuck13** [comment]
Ty for your contributions. Sorry for the delay, we are currently working on a few other projects but for the next week Ill test your pull request.

**Review by steuck13 — APPROVED** [review]

**Comment by emrebekar** [comment]
And there is also new changes. After your approval, i will push it to your repository.

**Comment by steuck13** [comment]
Greetings,
First of all: great work. I tested a lot of types and thye worked amazingly well. This review also allowed me to see a lot of issues that I'll have to change in this codebase in the near future, too many things that could be done in a better way.

I runned a few tests using the current version and a few tests with the changes from this pull request. My test environement is a Windows XP SP3 VM with a Matrikon OPC test server. The test involved reading a variable of each type, changing the value, and reading again to see if the changes were successfully written. My main finding was:
- 4-bytes Integers are having trouble on decoding/encoding, I'm not sure where this is happening but since there are a few changes on encoding/decoding I believe the problem might be there.

Thank you for your hard work and your contributions.

**Comment by emrebekar** [comment]
Hi Igor.

I have made some modifications after this pull request as well. Maybe, it
will resolve the issues. And i have added a new features for the currency
reading and writing.

Thanks for your interest.

Emre

Igor Steuck Lopes <notifications@github.com>, 25 May 2020 Pzt, 21:32
tarihinde şunu yazdı:

**Comment by steuck13** [comment]
Greetings, Emre,

The tests were made based on the commit d23d1aaea92396612dac72510bf26da2a539dd33 . I still have to test your currency implementation but the issues I had appeared in the latest version available. 

Best Regards
Igor

**Comment by emrebekar** [comment]
What kind of problem did you test? Maybe i can check out it as well.

**Comment by steuck13** [comment]
I installed our Node-RED node (`node-red-contrib-opc-da`) and changed the` node-dcom` directory so that the one with the changed was used. Now when I try to read the variable` Bucket Brigade.Int4` from the Matrikon OPC Server I get a weird number instead of the value saved there.

The variable in the server.
image

The Value returned when reading:
image

**Comment by emrebekar** [comment]
I have resolved the bug. But there is a new one. When i assign variable as a negative one, it subs the variable with maximum size. e.g "-3" value of 2 byte int returns as "65533".

**Comment by emrebekar** [comment]
By the way i will try to implement big int in order to get 64 bit datas. At least i will try. But there is a constraint. Big int is supported in node 10+ versions

**Comment by steuck13** [comment]
> I have resolved the bug. But there is a new one. When i assign variable as a negative one, it subs the variable with maximum size. e.g "-3" value of 2 byte int returns as "65533".

Yeah, probably being unsigned. Variant 2-bytes integers appear in two ways: VT_I2 and VT_UI2. If we are having problems with negative numbers we are actually doing the former one.

**Comment by steuck13** [comment]
> By the way i will try to implement big int in order to get 64 bit datas. At least i will try. But there is a constraint. Big int is supported in node 10+ versions

We talked about this kind of problem before but never really choose the best approach here. Indeed from version 10 onward this wouldn't be a problem. I believe this is deserves an issue for itself. Too big to be solved here. Thank you for bringing this topic btw.

**Comment by steuck13** [comment]
This list contains all the main types we are using here: https://www.opcsupport.com/s/article/What-are-the-OPC-Datatypes . Very useful.

**Comment by steuck13** [comment]
Greetings
So, a few things. Previously you mentioned BigInt, we are all-in for it. I believe it might make some stuff easier to do. I did a few tests on you commits and so far everything is working fine, great job. I'll do a few more tests tomorrow and then merge your code if no new errors are found.

Thank you once again for your contributions.

**Comment by emrebekar** [comment]
Hi Igor.

I have fixed the issue about all unsigned and singed integer. But not for
big integer i want to mention it. On the other hand there is another little
problem with adding items. when i tried to add mode than 170 tags i got an
error. When i checked the function which is calculating the bytes of
variables i saw some differences with the jinterop library. I am currently
working on it.
Igor Steuck Lopes <notifications@github.com>, 4 Haz 2020 Per, 15:35
tarihinde şunu yazdı:

**Pull request merged**
